### ISSUE TITLE
A possible bug in reset, vehicle initialization or velocity computing

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#273]
![image](https://user-images.githubusercontent.com/22206995/111056279-b9bdba80-84b8-11eb-8fd7-e42e4b75941d.png)

We can find that, along with the training, the minimal velocity in the episode across all sampled episodes is almost always greater than 0.5. That's quite weird! The vehicle may have emergence stop and so the velocity should be 0 at that time.

Here are some possible reasons:

* [ ] 1. During reset, the velocity of last episode is carried out to next episode.
* [ ] 2. The vehicle is always initialized with non-zero velocity (which is what we expected, at that can not explain the "emergence stopping issue"!)
* [ ] 3. The velocity is computed wrongly!

**Comment by lqy0057** [comment]
When the vehicle is static, the velocity is still > 0.5
![image](https://user-images.githubusercontent.com/24489294/111067347-d250c380-84fe-11eb-8a93-39a4c81a4769.png).

I find it is caused by z-speed
![image](https://user-images.githubusercontent.com/24489294/111067681-522b5d80-8500-11eb-9610-ae0451c3d39c.png)
