### ISSUE TITLE
Some bugs in MARL env

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#293]
Related to #292 

https://user-images.githubusercontent.com/22206995/111398125-d7c82c80-86fd-11eb-982f-bf9ac5bacb22.mp4

1. The window always hide to background, not sure why that happens. I have to hide the window in top (like the Pycharm window) so that I can see PGDrive.
2. Key strikes are all invalid. I can't press H(elp) or N(ext) or so.
3. The vehicle appears like a white box in left upper top-down view.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/22206995/111398277-1fe74f00-86fe-11eb-8d90-bd3dda42cd59.png">

**Comment by lqy0057** [comment]
1. It happens **occasionally** on Win10 and Ubuntu16.04,  and will throw a warning named: Fail to set foreground window. I think that Panda3d tries to do this, but fails due to system setting or some other stuff. 
2. I will check this problem and fix it on #292 
3. Actually, it is the lidar points covering the vehicle surface, and it is not a bug

**Comment by lqy0057** [comment]
Update:
2. The key pressing is valid on my machine. script: ```pgdrive/envs/generation_envs/multi_agent_pgdrive.py```

**Comment by pengzhenghao** [comment]
For problem 1, I think some process tries to pop up new window and takeover the priority. Maybe the experts? The rllib restored agent? 

Would random agent running two vehicles also raise this issues?

**Comment by lqy0057** [comment]
Actually, I only encountered this problem a few times. You could verify it by yourself. And I think it is not related to the expert since its appearance is irregular.
