### ISSUE TITLE
Improve efficiency for MARL rendering

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#351]
It is really slow for MARL rendering.

**Comment by pengzhenghao** [comment]
Profile:

![pgdrive23](https://user-images.githubusercontent.com/22206995/113707937-32f4aa00-9713-11eb-9678-6a510bfc8e3c.png)

**Comment by pengzhenghao** [comment]
I am not sure where consumes so many time, the renderFrame is called quite naturally I think..

**Comment by lqy0057** [comment]
Use script: marl_rouabout_env: _vis()

![image](https://user-images.githubusercontent.com/24489294/114979655-dab16b00-9ebd-11eb-92a8-e850c4358af6.png)
Use Pstats to find render problem is more reasonable since the igLoop() used to render in panda3d will sync the frame rate and your screen refresh rate. From the picture above, you can find a lot of time consumed to sync the screen.
Without this limit, the time consuming is acceptable.
![image](https://user-images.githubusercontent.com/24489294/114980138-9b374e80-9ebe-11eb-8e8c-fd499a587aa9.png)

**Comment by lqy0057** [comment]
Solved in #399

**Comment by pengzhenghao** [comment]
![tmp](https://user-images.githubusercontent.com/22206995/115489641-1b7afc80-a28f-11eb-8f59-1668fae7a4cd.png)


Today's profiling result.

I just can't find any place to improve!!

**Comment by pengzhenghao** [comment]
We can say that this issue is temporarily resolved! Since current Panda3D rendering in MA Env with 40 agents can already achieve 50+ FPS!
